Sunbird-RC/sunbird-rc-core

java/registry/src/main/java/io/opensaber/registry/controller/RegistryClaimsController.java
java/registry/src/main/java/io/opensaber/registry/helper/EntityStateHelper.java
java/registry/src/main/java/io/opensaber/registry/helper/RegistryHelper.java
java/registry/src/main/java/io/opensaber/registry/model/state/StateContext.java
java/registry/src/main/resources/public/_schemas/Common.json
java/registry/src/main/resources/public/_schemas/Student.json
java/registry/src/main/resources/public/_schemas/Teacher.json
java/registry/src/main/resources/workflow/statetransitions.drl

…or teacher | Add Guardian property

Introduce Notes in properties 

---

java/registry/src/main/java/dev/sunbirdrc/registry/Constants.java
java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryEntityController.java
java/registry/src/main/java/dev/sunbirdrc/registry/helper/RegistryHelper.java

Get Entity with Invalid Id and Security Disabled should give 404 error 

---

services/certificate-signer/api.yaml
services/certificate-signer/certificate-signer.ipynb
services/certificate-signer/config.json
services/certificate-signer/src/services/signerService.js
services/certificate-signer/tests/services/signerService.test.js

Adding api specification for signer

---

java/registry/src/main/java/dev/sunbirdrc/registry/config/SchemaLoader.java
java/registry/src/main/java/dev/sunbirdrc/registry/exception/SchemaException.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/SchemaService.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImpl.java
java/registry/src/main/java/dev/sunbirdrc/registry/util/DefinitionsManager.java
java/registry/src/main/java/dev/sunbirdrc/registry/util/DistributedDefinitionsManager.java
java/registry/src/main/java/dev/sunbirdrc/registry/util/IDefinitionsManager.java
java/registry/src/test/java/dev/sunbirdrc/registry/config/SchemaLoaderTest.java
java/registry/src/test/java/dev/sunbirdrc/registry/service/SchemaServiceTest.java
java/registry/src/test/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImplTest.java

- seperated validating schemas

- fixed loading schemas from DB

---

java/registry/src/main/java/dev/sunbirdrc/registry/config/SchemaLoader.java
java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryEntityController.java
java/registry/src/main/java/dev/sunbirdrc/registry/exception/SchemaException.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/NativeReadService.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/SchemaService.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/AuditDBWriter.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImpl.java
java/registry/src/test/java/dev/sunbirdrc/registry/config/SchemaLoaderTest.java
java/registry/src/test/java/dev/sunbirdrc/registry/service/SchemaServiceTest.java

https://github.com/Sunbird-RC/community/issues/315

Fixed issue #315

---

deps/keycloak/Dockerfile

- Custom keycloak image with NONCE validation made configurable

Update keycloak base image

---

imports/realm-export.json
java/apitest/src/test/java/e2e/registry/TeacherUniqueRequest.json
java/apitest/src/test/java/e2e/registry/registry.feature
java/apitest/src/test/resources/realm-export.json
java/middleware/registry-middleware/authorization/src/main/java/dev/sunbirdrc/registry/authorization/SchemaAuthFilter.java
test_environments/test_with_asyncCreate_events_notifications.env
test_environments/test_with_distributedDefManager_nativeSearch.env

Issue: https://github.com/Sunbird-RC/community/issues/777

Fixed schema name matching for schema auth filter

---

java/registry/src/main/java/dev/sunbirdrc/registry/helper/DidHelper.java
java/registry/src/main/resources/application.yml
java/registry/src/main/resources/internal/_schemas/Issuer.json

https://github.com/Sunbird-RC/community/issues/919

Create Issuer schema and Did helper

---

services/credential-schema/src/rendering-templates/validate-template.service.ts
services/credential-schema/src/schema/schema.controller.ts
services/credentials-service/src/credentials/credentials.service.ts
services/credentials-service/src/credentials/utils/rendering.utils.service.ts

resolves 
https://github.com/Sunbird-RC/community/issues/954
https://github.com/Sunbird-RC/community/issues/955

Fixed rendering credential template and update credential-schema

---

services/credentials-service/src/credentials/credentials.controller.ts
services/credentials-service/src/credentials/credentials.service.ts

Issue: https://github.com/Sunbird-RC/community/issues/957

[Feat] External templates support

---

services/credentials-service/src/credentials/documents.ts
services/identity-service/src/vc/documents.ts

Issue: https://github.com/Sunbird-RC/community/issues/968

added https://www.w3.org/ns/did/v1 response to support offline

---

docker-compose.yml
services/credentials-service/package.json
services/credentials-service/src/credentials/utils/rendering.utils.service.ts
services/credentials-service/yarn.lock

https://github.com/Sunbird-RC/community/issues/959

[ISSUE-959]: Added QR_TYPE configuration and W3C_VC qr type support

---

java/claim/pom.xml
services/encryption-service/pom.xml
services/id-gen-service/pom.xml

Issue: https://github.com/Sunbird-RC/community/issues/997

[FEAT]: added support for mssql for claims, encryption and id gen services

---

docker-compose-v1.yml
java/middleware-commons/src/main/java/dev/sunbirdrc/registry/middleware/util/OSSystemFields.java
java/middleware/registry-middleware/workflow/src/main/java/dev/sunbirdrc/workflow/StateContext.java
java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryController.java
java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryEntityController.java
java/registry/src/main/java/dev/sunbirdrc/registry/helper/RegistryHelper.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImpl.java
java/registry/src/main/java/dev/sunbirdrc/registry/util/PrivateField.java
java/registry/src/test/java/dev/sunbirdrc/registry/helper/RegistryHelperTest.java

Fixed multiple credentials creation and revocation on update entity

---

java/registry/src/main/java/dev/sunbirdrc/registry/service/DIDService.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/SignatureV2ServiceImpl.java
java/registry/src/test/java/dev/sunbirdrc/registry/service/CredentialSchemaServiceTest.java
java/registry/src/test/java/dev/sunbirdrc/registry/service/DIDServiceTest.java
java/registry/src/test/java/dev/sunbirdrc/registry/service/impl/SignatureV2ServiceImplTest.java

https://github.com/Sunbird-RC/community/issues/922

Credential services integration with registry unit tests

---

java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryController.java
java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryEntityController.java
java/registry/src/main/java/dev/sunbirdrc/registry/helper/RegistryHelper.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/NativeSearchService.java
java/registry/src/test/java/dev/sunbirdrc/registry/helper/RegistryHelperTest.java

https://github.com/Sunbird-RC/community/issues/1008

[BUG][LTS-2.X]: Fixed not getting private fields in Get Entity response

---

docker-compose.yml
java/middleware-commons/src/main/java/dev/sunbirdrc/registry/middleware/util/JSONUtil.java
java/pojos/src/main/java/dev/sunbirdrc/pojos/APIMessage.java
java/registry/src/main/java/dev/sunbirdrc/registry/helper/RegistryHelper.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/CredentialSchemaService.java
services/identity-service/src/vc/vc.service.ts

- Encryption service env in registry docker compose
- Credential template null error
- Audit logs not returning error

[BUG]: Minor bug fixes

---

java/middleware-commons/src/main/java/dev/sunbirdrc/registry/middleware/util/JSONUtil.java
java/registry/src/main/java/dev/sunbirdrc/registry/controller/RegistryUtilsController.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/AuditDBImpl.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/AuditFileImpl.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/AuditServiceImpl.java
java/registry/src/main/java/dev/sunbirdrc/registry/util/AuditFileWriter.java
java/registry/src/main/resources/application.yml

https://github.com/Sunbird-RC/community/issues/1010

[FEAT]: added support for vc for audit logs

---

services/credentials-service/prisma/migrations/20240517192358_expiration_date_change/migration.sql
services/credentials-service/prisma/schema.prisma

https://github.com/Sunbird-RC/community/issues/1011

[BUG]: removed expiration date as mandatory field

---

java/registry/src/main/java/dev/sunbirdrc/registry/service/DecryptionHelper.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/NativeSearchService.java

https://github.com/Sunbird-RC/community/issues/1013

[BUG]: fixed decryption in list entity api

---

services/identity-service/docker-compose-test.yml
services/identity-service/docker-compose.yml
services/identity-service/src/did/did.controller.ts
services/identity-service/src/did/did.service.spec.ts
services/identity-service/src/did/did.service.ts
services/identity-service/src/did/dtos/GenerateDidRequest.dto.ts

https://github.com/Sunbird-RC/community/issues/1021

[BUG]: fixed generate request swagger payload

---

java/middleware/registry-middleware/authorization/src/main/java/dev/sunbirdrc/registry/authorization/SecurityConfig.java
java/middleware/registry-middleware/workflow/src/main/java/dev/sunbirdrc/workflow/RuleEngineService.java
java/middleware/registry-middleware/workflow/src/main/java/dev/sunbirdrc/workflow/StateContext.java
java/middleware/registry-middleware/workflow/src/main/resources/workflow/statetransitions.drl
java/registry/src/main/java/dev/sunbirdrc/registry/config/GenericConfiguration.java
java/registry/src/main/java/dev/sunbirdrc/registry/helper/EntityStateHelper.java
java/registry/src/main/resources/public/swagger-ui.html
java/registry/src/test/java/dev/sunbirdrc/registry/helper/EntityStateHelperTest.java
java/registry/src/test/java/dev/sunbirdrc/registry/helper/RegistryHelperTest.java

https://github.com/Sunbird-RC/community/issues/876

[BUG]: Auth Health check process fixed

---

java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/SignatureV2ServiceImpl.java

https://github.com/Sunbird-RC/community/issues/1024

[BUG]: Fixed multiline templates not rendering

---

services/credentials-service/src/credentials/credentials.controller.ts

https://github.com/Sunbird-RC/community/issues/1031

[BUG]: Fixed template id required error for only qr code generation

---

java/registry/src/main/java/dev/sunbirdrc/registry/config/KafkaConfiguration.java
java/registry/src/main/java/dev/sunbirdrc/registry/consumers/CreateEntityConsumer.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/KafkaHealthService.java
java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/KafkaEventService.java

https://github.com/Sunbird-RC/community/issues/1032

[BUG]: kafka topics issue for notification and metrics service fixed

---

java/registry/src/main/java/dev/sunbirdrc/registry/service/impl/RegistryServiceImpl.java

https://github.com/Sunbird-RC/community/issues/1033

[BUG]: Fixed hard delete not working for redundant entity properties

---

java/registry/src/main/java/dev/sunbirdrc/registry/helper/RegistryHelper.java

https://github.com/Sunbird-RC/community/issues/1034

[BUG]: Fixed attestation null pointer exception
